### ISSUE TITLE
Handle bar numbers in GridLY cells

### ISSUE THREAD

**Issue by uliska** [openlilylib/snippets#101]
When using `\gridSetRange` there's an issue with barnumbers because they're not changed. So the retrieved music doesn't have a notion that it is starting from somewhere in the score.

This means that displayed barnumbers will be wrong, and that barnumber checks defined in the music or templates will fail.

I suggest:
- add a `barnumber` property to the ones accepted in the `\with  {}` block.
- when using `\gridSetRange` prepend a `\set Score.currentBarNumber` to the first cell's music (when defined in the cell or in the template).
- when using `\gridGetMusic` prepend a `\barNumberCheck #NN` to each cell's music.

The barnumber to be used should be the one at the beginning of the content (ignoring the `opening`).
This would encourage people to use barnumber checks and relieve them from entering them _inside_ the music definitions.

**Comment by Cecca** [comment]
You are right. As of now I wasn't affected by this issue because my "La Bomba" project has all the bar numbers set inside the opening and in the music definition, as you can see [here](https://github.com/Cecca/la-bomba-ensalada/blob/de0dc68e23a285a24e10bde247c780e6b1b498ad/parts/tenor/10.ily#L38). So I failed to identify this issue.

I like your suggestion of adding a property to the `\with {}` block. This way one can define bar numbers in the template definition and have it used by all the other parts.

I'll think about the best way to do this, an implementation should be ready in the weekend.

**Comment by Cecca** [comment]
@uliska please have a look at the changes in 14c763021dfcd53733bb2147ca6a5adfdb84f688. That should fix the issue

**Comment by uliska** [comment]
Yes, it does..
