### ISSUE TITLE
Well formed commit messages

### ISSUE THREAD

**Issue by Cecca** [openlilylib/snippets#59]
Since OpenLilyLib contains many different libraries and components, it's desirable that commit messages start with a name identifying the component (just like here: eb8f1fcffe3dedcbeb363134408af72a36c86da1).

However I usually keep forgetting to adhere to such policies, resulting in ill-formed commit messages, just like this one: 3e9c6aaf6411458707b06457d4a7693c28ec9ee6 (sorry about that).

The following git hook can help getting consistent commit messages

``` bash
#!/bin/bash
#
#                  Well-formed commit messages hook
#                  ================================
#
# This git hook checks whether the message of the commit is well
# formed, that is, if it starts with the name of the OpenLilyLib
# component the commit refers to. Here, component refers either to a
# library contained in the `ly` directory or to some other part of
# OpenLilyLib, like `meta`.
#
# To make an example, commits relative to GridLY should look like
#
#     GridLY: a commit message
#
# and commits for ScholarLY should be something loke
#
#     ScholarLY: another commit message
#
# Once this hook is enabled, it will check commit messages before the
# commit is finalized. If the commit message does not start with the
# component name, then the commit is aborted.
#
# The behaviour of the hook is controlled via the variable
# `OLL_COMPONENT`, that can be in one of three states:
#
#   - unset: in this case the hook will throw an error, asking the
#            user to set the variable with
#
#                   export OLL_COMPONENT=component_name
#
#   - set to "": in this case no check will be performed. So, to
#                disable the hook, it is sufficient to issue the
#                following command on the terminal
#
#                   export OLL_COMPONENT=""
#
#                before doing the commit.
#
#   - set to some name: the hook will check that the first line of the
#                       commit message starts with the right component
#                       name, followed by a colon.
#
# To enable this hook, save this file as ".git/hooks/commit-msg".
#
#


# The variable OLL_COMPONENT is unset
if [[ ! ${!OLL_COMPONENT[@]} ]]
then
    echo >&2 "Before commiting, you should set the OpenLilyLib component"
    echo >&2 "you are working on, by setting the environment variable"
    echo >&2 ""
    echo >&2 "    OLL_COMPONENT"
    echo >&2 ""
    echo >&2 "If you prefer not to have commit messages checked, then"
    echo >&2 "set OLL_COMPONENT to the empty string, with"
    echo >&2 ""
    echo >&2 "    export OLL_COMPONENT=\"\""
    exit 1
# The variable OLL_COMPONENT is set to the empty string
elif [[ -z $OLL_COMPONENT ]]
then
    echo >&2 "Variable OLL_COMPONENT is unset, skipping commit message check"
    exit 0
# The variable OLL_COMPONENT is set, go on with the check
else
    head -n 1 "$1" | grep "^$OLL_COMPONENT:" || {
        echo >&2 "[ERROR] Commit aborted."
        echo >&2 "The commit message should start with '$OLL_COMPONENT:'"
        exit 1
    }
fi
```

By saving the above code to `.git/hooks/commit-msg` in the local repository, commits not starting with the value of the `OLL_COMPONENT` environment variable will be rejected.

I find this snippet really useful, should we include it in the `meta` section of OpenLilyLib?

**Comment by uliska** [comment]
Looks like a good idea, unfortunately I don't have time to test now.

**Comment by uliska** [comment]
But you can make it a pull request. Maybe someone else will have a look and handle it.

**Comment by uliska** [comment]
Now I've read the script and I have one issue with it: it requires the committer to _maintain_ that environment variable. As it is I think the script is only working for people who contribute to one library exclusively.

Would it be feasible to perform the check against the affected files? I think about checking if all affected files in the commit are inside one library and then take the top-level directory name as the test condition. This could fail because
- not all files are inside one library (e.g. when code is moved to the shared `_internal` library)
- the commit message doesn't start with the filename.

In that case the error message should tell the committer that the committ message is ambiguous, but it should be possible to commit anyway (i.e. provide a "Do you still want to commit with that message (y/n)?" input).

Maybe we should add another use case when the commit message starts with _one_ out of the affected libraries (e.g. affected files are from `gridly` and `_internal`, and the commit message starts with `gridly:`) In that case a different, less alarming message should be used, along the lines of "are you sure?".

While we're at it: that could then of course be extended:
- offer the option to _update_ the commit message (I think the commit message is a _file_ (?) so it should be possible to modifiy it during the hook execution)
- test also for the length of the first line (should be <= 50 characters)

**Comment by Cecca** [comment]
I should have a look at it, I'm not an expert of git hooks. I'll let you know if I find a way to make it work this way :-)

**Comment by Cecca** [comment]
Before I start to work on it, I have a few comments on you observations

> Would it be feasible to perform the check against the affected files?

I think this can be done pretty easily. However, I think that it's more desirable to let the developer mark the commit as belonging to any of the projects involving the files, like you suggested. Usually commits are supposed to concern a set of related features, so if someone updated files from different projects in one commit, it probabily was for a single project's sake. So the behaviour of the hook should be along this line: if the commit message starts with the name of the project containing any of the files involved, then proceed without error, otherwise fail, warning the user that an appropriate labelling of the commit is missing.

> but it should be possible to commit anyway

Checks implemented with commit hooks can be skipped with the `--no-verify` option.

> provide a "Do you still want to commit with that message (y/n)?" input

I think that interactive input should be avoided. While this is fine when using git from the command line, it may cause cause problems to people using git via other programs. For instance I use Emacs to manage git repositories, and having the hook ask for some input will cause the commit process to hang.

> offer the option to update the commit message

Like the previous point, I think that the hook should be a simple _filter_. Of course, if we can make the hook save the failing commit message somewhere so that the developer can correct it, that would be wonderful.

> test also for the length of the first line (should be <= 50 characters)

This can be surely done

**Comment by uliska** [comment]
> ```
> Would it be feasible to perform the check against the affected files?
> ```
> 
> I think this can be done pretty easily. However, I think that it's 
> more desirable to let the developer mark the commit as belonging to 
> any of the projects involving the files, like you suggested. Usually 
> commits are supposed to concern a set of related features, so if 
> someone updated files from different projects in one commit, it 
> probabily was for a single project's sake. So the behaviour of the 
> hook should be along this line: if the commit message starts with the 
> name of the project containing any of the files involved, then proceed 
> without error, otherwise fail, warning the user that an appropriate 
> labelling of the commit is missing.

OK, I see. Then we don't need to check for files at all. I know this is 
as simple as firing the right git command but interpreting the results 
might be still tricky.
So the rule should be: The commit prefix has to be the name of one of 
the top-level directories (below /ly) plus the colon.

> ```
> but it should be possible to commit anyway
> ```
> 
> Checks implemented with commit hooks can be skipped with the 
> |--no-verify-option|.

OK, but that's not the issue here. The question is how to proceed after 
a failure condition is detected.

> ```
> provide a "Do you still want to commit with that message (y/n)?" input
> ```
> 
> I think that interactive input should be avoided. While this is fine 
> when using git from the command line, it may cause cause problems to 
> people using git via other programs. For instance I use Emacs to 
> manage git repositories, and having the hook ask for some input will 
> cause the commit process to hang.
> 
> ```
> offer the option to update the commit message
> ```
> 
> Like the previous point, I think that the hook should be a simple 
> /filter/.

OK, I see and agree.

> Of course, if we can make the hook save the failing commit message 
> somewhere so that the developer can correct it, that would be wonderful.

Actually I think this would be a requirement for the hook to be 
accepted. Writing a commit message _can_ be a laborious task, and having 
to be aware that the hook may completely discard that work may be 
contraproductive.
The file should be a file that isn't tracked (i.e. we add it to 
.gitignore) and either be located in the root directory or in the 
current directory. The warning should then inform the user that "git 
commit -F OUR_FILE_NAME" can be used to reuse the commit message.

**Comment by PaulMorris** [comment]
> On Feb 19, 2015, at 5:33 PM, Urs Liska notifications@github.com wrote:
> 
> The commit prefix has to be the name of one of 
> the top-level directories (below /ly) plus the colon.

For rare cases where changes aren’t tied to a particular library, it would be good to have a general “catch-all” type prefix to use (maybe “oll:” or something else…?).  No need to force a commit to be tied to one library if that’s not actually the case.  Just a suggestion, FWIW.

**Comment by uliska** [comment]
Good catch.
Another thing I had already thought about is adding something like an alist matching library/directory names with acceptable abbreviations. But this could be made somewhat more general by having a list with prefixes that can be checked against in addition to the existing top-level directories

**Comment by Cecca** [comment]
Thanks for all the suggestions, I opened a pull request, see #70 

> For rare cases where changes aren’t tied to a particular library, it would be good to have a general “catch-all” type prefix to use (maybe “oll:” or something else…?). 

As of now the prefix is mandatory only if library files are included in the commit. So any prefix can be used in those cases :smiley:
